# Generated by Django 4.0.4 on 2022-05-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModels',
            new_name='BlogModel',
        ),
    ]
